name: ${GLOBAL_NAME}

services:
  papercut:
    container_name: ${PAPERCUT_CONTAINER_NAME}
    image: ${PAPERCUT_IMAGE_NAME}:${PAPERCUT_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - TZ=${TIMEZONE}
    ports:
      - ${PAPERCUT_HTTP_PORT}:9191
      - ${PAPERCUT_HTTPS_PORT}:9192
      - ${PAPERCUT_RPC_PORT}:9193
    volumes:
      - papercut_data:/papercut/server/data
      - papercut_logs:/papercut/server/log
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9191"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

networks:
  default:
    name: ${PAPERCUT_CONTAINER_NAME}_network
    driver: bridge

volumes:
  papercut_data:
    name: ${PAPERCUT_CONTAINER_NAME}_data
    driver: local
  papercut_logs:
    name: ${PAPERCUT_CONTAINER_NAME}_logs
    driver: local