version: '3.9'
services:
  web:
    image: hp41/papercut-mf:latest
    container_name: papercut
    restart: always
    ports:
      - ${HTTP_PORT}:9191
      - ${HTTPS_PORT}:9192
      - ${RPC_PORT}:9193
    networks:
      - default
    volumes:
      - ./data:/papercut/server/data
      - ./log:/papercut/server/log

networks:
  default:
    name: docker_papercut_network
    driver: bridge

volumes:
  data:
    name: docker_papercut_data
    driver: local
